### ISSUE TITLE
`emit` `emitLocal` and `emitRemote` should accept callback

### ISSUE THREAD

**Issue by Haocen** [fent/clusterhub#8]
In order to simulate remote function call:
```
// worker
hub.emit('masterFunc', args, function() {
  hub.on('masterFuncReturn', function(result) {
    console.log(result);
  });
});

// master
hub.on('masterFunc', function(args) {
  hub.emit('masterFuncReturn', masterFunc(args));
});

**Comment by fent** [comment]
The other functions have callbacks because EventVat functions can return values. So calling `hub#get('key')` you'd expect a key value.

```js
hub.get('key', function(value) {
});
```

But for the emit functions, what would you expect back? I could pass the callback to [process.send()], which will call callback after a successful message sent. Is this what you're aiming for?

**Comment by claudianus** [comment]
hi @fent i have the same opinion with him. i guess he's talking about something like this

A worker
```javascript
hub.emit('msg', 'hello', function(response) {
    console.log(response)
})
```

B worker
```javascript
hub.on('msg', function (data. callback) {
    if(data === 'hello') {
        callback('world')
    }
})
```

it will be more useful and powerful how do you think about it? @fent would you please do this

**Comment by fent** [comment]
Ok, so this is possible now in the latest release. Try it in v1.0.0. It accepts any number of function arguments.
